# Generated by Django 5.1 on 2024-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authors_categories_faqs_projects_propertytypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='image',
            field=models.ImageField(upload_to='feeds/'),
        ),
    ]
