# Generated by Django 5.1 on 2024-09-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_feeds_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='avatar',
            field=models.ImageField(upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='teammembers/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='teammembers/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='image',
            field=models.ImageField(upload_to='ratings/'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(upload_to='teammembers/'),
        ),
        migrations.AlterField(
            model_name='testemonials',
            name='image',
            field=models.ImageField(upload_to='testemonials/'),
        ),
    ]
